# Generated by Django 6.1.1 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
